version: "3.8"
services:
  maven-build2:
    container_name: maven-build2
    build:
      context: .
      dockerfile: ./docker/maven-build/Dockerfile
    volumes:
      - my-data:/src/dist
      - maven-repo:/root/.m2

  tomcat-server:
    container_name: tomcat-server
    build:
      context: .
      dockerfile: docker/tomcat/Dockerfile
    ports:
      - "8020:8080"
      - "9999:9999"
    volumes:
      - my-data:/usr/local/tomcat/webapps
    depends_on:
      - maven-build2

volumes:
  my-data:
    name: my-data
  maven-repo:
    name: maven-repo

